CREATE TABLE IF NOT EXISTS usuarios (
    USU_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USU_LOGIN TEXT NOT NULL UNIQUE,
    USU_SENHA TEXT NOT NULL,
    USU_NOME TEXT NOT NULL,
    USU_EMAIL TEXT NOT NULL UNIQUE,
    USU_PRIMEIRO_ACESSO INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS produtos (
    PDT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PDT_DESCRICAO TEXT NOT NULL,
    PDT_PRECO REAL NOT NULL,
    PDT_QUANTIDADE INTEGER NOT NULL DEFAULT 0
);
